### ISSUE TITLE
Simple-Blog needs comments and closed comments always

### ISSUE THREAD

**Issue by aleskinen** [Typesetter/Simple-Blog#2]
Otherwise it complaints that undefined index comment_count and closed_comments even when commenting is disabled. It also shows comment_count even though commenting is disabled. 

New Post is not translatable and on archives name on archive is always in english like january.

**Comment by oyejorge** [comment]
I just uploaded version 3.0.2 to TypesetterCMS.com with the fixes for these bugs. 

The archive gadget now uses the strftime() method to get the month name. This is the same method that's used to get the formatted published date for blog posts.

Thanks!
